---
name: johnsy.com
title: parkrun Userscripts
description: A collection of userscripts that enhance parkrun pages with additional statistics, visualisations, and challenges
description_html: |
  parkrun Userscripts: Enhance your parkrun experience with additional
  statistics, visualisations, and unofficial challenges.
baseurl: /tampermonkey-parkrun
url: https://johnsy.com

apple_touch_icon_sizes:
  - 57
  - 60
  - 72
  - 76
  - 114
  - 120
  - 144
  - 152

favicon_sizes:
  - 16
  - 32
  - 96
  - 128
  - 196

mstile_sizes:
  - { type: square70x70logo, dimensions: '70x70' }
  - { type: square150x150logo, dimensions: '150x150' }
  - { type: wide310x150logo, dimensions: '310x150' }
  - { type: square310x310logo, dimensions: '310x310' }

include:
  - icons
  - images

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
